# p 34
# Filename: limit_req.conf

# I decided to place the global rate limiting configuration in a separate file
# On a classic VPS, instructions here should be placed in /etc/nginx/nginx.conf inside the http { } block

# Define global limit_req zone
# This simply limits each unique IP address ($binary_remote_addr) to 60 requests per minute -> 1 request per second on average
limit_req_zone $binary_remote_addr zone=req_limit:10m rate=60r/m;

limit_req_status 429;