# # Consult p34
# server {
#     listen 80;
#     listen  [::]:80;

#     add_header X-Upstream $hostname;
#     server_name static.localhost;
#     # index index.html;

#     location / {

#         root /var/www/html;
#         index index.html index.htm;
        
#     }

#     error_page 404 /404.html;
#     error_page 500 502 503 504  /50x.html;

# }

# /etc/nginx/conf.d/static.localhost.conf
server {
    listen 80;
    listen [::]:80;

    add_header X-Upstream $hostname;
    server_name static.localhost;

    location / {
        root /var/www/html;
        index index.html index.htm;

        # Apply rate limiting
        # This references the global zone "mylimit" (see below)
        # burst allow x extra requests 
        # Ex: if the rate is 1r/s and burst=5, a client can make 6 requests in a second before being limited
        # limit_req zone=req_limit burst=5 nodelay;
        limit_req zone=req_limit;
    }

    error_page 404 /404.html;
    error_page 429 /429.html;
    error_page 500 502 503 504 /50x.html;
}
