FROM nginx:1.29

WORKDIR /var/www/html

RUN mkdir -p /var/www/html/website
# COPY ./website /var/www/html/website

# COPY ./static.localhost.conf /etc/nginx/conf.d/static.localhost.conf
RUN rm /etc/nginx/conf.d/default.conf