FROM nginx:1.29

WORKDIR /var/www/html
# /etc/nginx
# /usr/share/nginx/html

# COPY . /var/www/html

# COPY ./static.localhost.conf /etc/nginx/conf.d/static.localhost.conf
RUN rm /etc/nginx/conf.d/default.conf